### PR TITLE
added secondary sorting

### PR DESCRIPTION
**Pull request by melalj**
Related to #37

### CODE REVIEW

**Comment by melalj** [comment]
I removed the support of a disabled sorting. We're forcing a default sorting (first column ascending). So on the 3rd click doesn't disable the sorting.

**Comment by melalj** [comment]
Fixed on e0dc425

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - yes, firefox works now, but only for primary sort.  how do I enable/access secondary sort?

**Comment by melalj** [comment]
You click on a column header to set the primary sort. Then you maintain the shift key, and you click on another column header for the secondary sorting

**Comment by Ths2-9Y-LqJt6** [comment]
ah - I see now.  It does indeed work - awesome. It needs some clean up though:
* on our example page, if you  click on Long and then shift City, Region and Country it both highlights text and leaves sort arrows in it's wake.  The end result should be primary sort by Long and secondary sort by Country, no arrows on region or city and no highlighted text: 
hightlighted multi arrows . To see desired behavior in action, check out http://tablesorter.com/docs/ which also uses shift click for secondary sort.
* secondary sort only works on like columns (eg. text + text) and unlike columns (eg text + numbers).  so if I primary sort on Country then secondary on Region, all good.  If I primary on City and the Secondary on Long, secondary fails.  Oh wait!  It's just the Long and Lat columns.  Traf and City works (and City and Traf).  Maybe it's endemic to our example page?  Either way, we should call it out i the docs so folks know how to fix it if need be or do a code fix so it always works as expected.

**Comment by melalj** [comment]
I just removed the user-select on 75c1a97

Normally we auto detect the column format if it's not specified, but I didn't take into consideration signed float. Fixed on b2f090a

**Comment by Ths2-9Y-LqJt6** [comment]
We're closer!  In chrome this works as expected (no selected text and all columns sort correct).  However it still shows arrows for columns that are not sorted:

multiple arrows

Desired behavior is to only have sort arrows for primary and secondary columns.

In IE11, FF and Safari none of the fixes work :(

**Comment by Ths2-9Y-LqJt6** [comment]
oh!  secondary sort doesn't work at all in Safari :(

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - not there yet :(

Chrome, FF, Edge, IE11 & safari: secondary sort does not work
Edge, IE11: text is still highlighted on column heads

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 This is weird. I tried on FF, Safari and Chrome and it works for me. Even the un-highlighted columns for IE11.
Can you double check if you got the latest version (branch dev-37) and provide me detailed steps to reproduce.

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - ok!  I nuked my install and re-installed and then grepped for a change from 4a9f716, specifically [line 192](https://github.com/Packet-Clearing-House/maptable/pull/63/commits/4a9f7161656a40262170c6a76a33e9b16b6ed2d0#diff-7d12218e29d596148ef20ac652d3a3b9R193),  to ensure gulp had build the ''dev/maptable.js'' file correctly.  As well, I grepped the maptable.js file served to the browser.  I'm on the right branch!

```
$ grep -ir 'this.sorting\[1\] = ' dev/maptable.js
this.sorting[1] = sortValue;
```

three things I found:
1. CSS cachng prevented the anti-select from working in FF, Safari and chrome (sorry!!!)
1. I was clicking on *really* bad primary and secondary sort (eg latitude then city) which made it look like it wasn't working, but in fact there simply was no change when secondary sorting.  Indeed secondary sort works. Note to self: a good test is Region then Country. (sorry again!!)
1. column selecting is still indeed broken on ie11 and edge. here's a screenshot from Edge 25.10586.672.0 showing selected columns and also showing the new styles in the inspector: selected edge

**Comment by melalj** [comment]
The "un-selection" should be working now on Edge:
screen shot 2017-04-21 at 9 59 06 pm

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj thanks!  I'll review latest fixes and get back to you.

**Comment by Ths2-9Y-LqJt6** [comment]
w00t!  Finally got around to testing this and it's all good.  thanks and sorry for the delay.

**Pull request merged**
