### PR TITLE
#51 try to fix heatmap in ie11

### PR DESCRIPTION
**Pull request by Ths2-9Y-LqJt6**

### CODE REVIEW

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 Any updates on this?
is it a fix for https://github.com/Packet-Clearing-House/maptable/issues/51

**Comment by Ths2-9Y-LqJt6** [comment]
sadly no, it does not fix it :(

**Comment by Ths2-9Y-LqJt6** [comment]
just confirming that as of now, PR #52 still doesn't fix #51

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 Can you tell me more what's the issue with IE11?

**Comment by Ths2-9Y-LqJt6** [comment]
Yups! Here's a screenshot:

ie11 fail

That all said, you will need to install IE11 some how to debug this ;)

**Comment by melalj** [comment]
Okay, I think I know what was the problem (fixed on ae13b14).
It would take me more time to set up the IE testing environment. Do you mind to test with the new edit?

**Comment by Ths2-9Y-LqJt6** [comment]
Still broken, but in a different way:

ie all filled

**Comment by melalj** [comment]
Okay, after debuging I just found out what's the problem (btw [BrowserStack](https://www.browserstack.com/start#os=Windows&os_version=7&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Flocalhost%3A5000%2Fheatmap.html&speed=1&host_ports=google.com%2C80%2C0) is super straightforward).
IE11 Doesn't support blending modes in Canvas, which is the base of the heatmap rendering algorthim:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/compositingandblendingincanvas2d/

I'm looking for work arounds but it will make things more complicated :(

**Comment by Ths2-9Y-LqJt6** [comment]
ok - let us know what you find.  as well, i'll ping woody to see what he thinks if we can't get ie11 working

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - I checked in with woody and he's OK if we make a best effort to just die gracefully: let folks know that IE11 and below don't work and to try any other browser.

**Comment by melalj** [comment]
Okay, I just made the changes to let the folks that IE11 or less is not supported (0d0c1ad):
screen shot 2017-04-14 at 6 45 59 pm

**Comment by Ths2-9Y-LqJt6** [comment]
awesome - works as expected.  Thanks @melalj !

**Pull request merged**
