### PR TITLE
added colorStrength heatmap parameter

### PR DESCRIPTION
**Pull request by melalj**

### CODE REVIEW

**Comment by melalj** [comment]
Related to #58

**Comment by Ths2-9Y-LqJt6** [comment]
k - cool, to answer #58's question, "what's the best way to tweak the fall off of a data point? " you added ``fallOffStrenght``, gotcha.  I loaded up dev-58 branch and played with the value.  Setting it to 0 and I still saw colors - I would have expected none.  Setting it to 1000 I would have expected it to cover the globe, but it only goes about say...45 degrees or so.   The difference between 1 and 0.5 seems too small as well.  

Either way - be sure to update README.md.  I may actually be using it wrong as I don't know what the readme would say ;)

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 I just updated the behavior to make it easier to configure

- `heatmap.colorStrength:` _(float, default: 1)_ Adjusts heatmap color strength, (0 make things transparent, 1 normal behavior, > 1 to make the color darker)

**Comment by Ths2-9Y-LqJt6** [comment]
i had to merge master to dev-58 to get it to compile.  testing ``colorStrength`` does not do anything.  values of 0,1 or 10 load the same map. maybe commits from PR #56  broke this PR?

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 Since you merged dev-56 to master, I set the base branch for this PR as master.
That's surprising, I just launched the `/heatmap.html` example and colorStrenght seems to have an effect:

screen shot 2017-04-05 at 4 48 09 pm

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - agreed - it does work! I must have not pulled latest code.  Thanks very for re-testing and sending along the screen shot of the different values for me to easily test against.

**Pull request merged**
